// Generated by mikser-io-schemas. Do not edit by hand.

import type { z } from 'zod'
import AuthorSchema from './schemas/author.js'
import PostSchema from './schemas/post.js'

export type AuthorMeta = z.infer<typeof AuthorSchema>
export type PostMeta = z.infer<typeof PostSchema>

export interface LayoutMap {
    'author': AuthorMeta
    'post': PostMeta
}

export type LayoutName = keyof LayoutMap
export type MetaByLayout<L extends LayoutName> = LayoutMap[L]
